logging:
  level:
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR

spring:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
    database: POSTGRESQL
    show-sql: true
#    hibernate:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/carbonfinal
    username: postgres
    password: 12345678
    driverClassName: org.postgresql.Driver
  security:
    user:
      password: password